In [1]:
import numpy as np
def rotx(theta):
    Rx = np.matrix([[1, 0, 0],
                   [0, np.cos(theta), -np.sin(theta)],
                   [0, np.sin(theta), np.cos(theta)]])
    return Rx
R = rotx(np.pi/6)
R

matrix([[ 1.       ,  0.       ,  0.       ],
        [ 0.       ,  0.8660254, -0.5      ],
        [ 0.       ,  0.5      ,  0.8660254]])

In [98]:
def trans(R, t):
    return np.block([[R, t.reshape(3,1)],
                     [np.array([0, 0, 0, 1])]])
tco = np.array([0, 0, 1])
T = trans(R, tco)
T

matrix([[ 1.       ,  0.       ,  0.       ,  0.       ],
        [ 0.       ,  0.8660254, -0.5      ,  0.       ],
        [ 0.       ,  0.5      ,  0.8660254,  1.       ],
        [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [86]:
#point p in camera frame
ro = np.array([0, 0, 1])
rop_tilde = np.block([ro, 1]) 
rcp = np.dot(T, rop_tilde)
rcp_1d = np.ravel(rcp[:, :3])
print("point p in camera frame \n", rcp_1d)

point p in camera frame 
 [ 0.        -0.5        1.8660254]


In [90]:
#normalized image coordinates:
def norm_image_coord(r):
    return np.array([r[0]/r[2], r[1]/r[2], 1])
s = norm_image_coord(rcp_1d)
print("normalized image coordinates: \n", s)

normalized image coordinates: 
 [ 0.         -0.26794919  1.        ]


In [97]:
#pixel coordinates:
K = np.matrix([[1500, 0, 640], 
               [0, 1500, 512], 
               [0, 0, 1]])
p = np.dot(K, s)
p = np.ravel(p)
print("pixel coordiniates: \n", p)


pixel coordiniates: 
 [640.         110.07621135   1.        ]
