In [4]:
import numpy as np

#task 2a
np.set_printoptions(formatter={'float': '{:0.9f}'.format})
x = np.array([[0, 0, 1],
              [1, 0, 1],
              [1, 1, 1],
              [0, 1, 1]])

xp = np.array([[1, 0, 1], 
               [2, 0, 1], 
               [1, 1, 1],
               [0, 1, 1]])
H = np.linalg.lstsq(x, xp, rcond=1)
H = H[0]
print("H from least square \n", H, "\n")

A = H[:2, :2].T
U,S,V = np.linalg.svd(A)
print("\n A matrix is found from H: \n", A)

#task 2B:
R = U @ V.T


print("\n R from polar decomposition \n", R)
P = np.linalg.inv(R) @ A
print("\n P matrix : \n", P)
angle = np.arccos(R[0, 0])
print("\n rotation angle is ", np.degrees(angle))


H from least square 
 [[1.000000000 -0.000000000 -0.000000000]
 [-1.000000000 1.000000000 0.000000000]
 [1.000000000 -0.000000000 1.000000000]] 


 A matrix is found from H: 
 [[1.000000000 -1.000000000]
 [-0.000000000 1.000000000]]

 R from polar decomposition 
 [[0.894427191 -0.447213595]
 [0.447213595 0.894427191]]

 P matrix : 
 [[0.894427191 -0.447213595]
 [-0.447213595 1.341640786]]

 rotation angle is  26.56505117707795
